import {addMDHOC} from './addMDHOC';
import {Simple} from './a_simple';
import {RichUtilsSample} from './b_rich-utils';
import {Blockfn} from './c_blockfn';
import {ContentStateView} from './contentstate-view';
import {SelectionStateView} from './selectionState-view';
import {CreateContentState} from './createContentState';
import {Entity} from './entity';
import {RegexDecorator} from './regexDecorator';
import {HashtagDecorator} from './hashtagDecorator';
import {ComplexDecorator} from './ComplexDecorator';

export const SimpleWithDoc = addMDHOC(Simple,  '/docs/simple.md');
export const SimpleDecoratorWithDoc = addMDHOC(RegexDecorator,  '/docs/placeholder.md');
export const HashtagDecoratorWithDoc = addMDHOC(HashtagDecorator,  '/docs/placeholder.md');
export const EntitySampleWithDoc = addMDHOC(Entity,  '/docs/entity.md');
export const RichUtilsSampleWithDoc = addMDHOC(RichUtilsSample, '/docs/placeholder.md');
export const BlockfnWithDoc = addMDHOC(Blockfn, '/docs/placeholder.md');
export const ContentStateViewWithDoc = addMDHOC(ContentStateView, '/docs/contentState.md');
export const SelectionStateViewWithDoc = addMDHOC(SelectionStateView, '/docs/selectionState-view.md');
export const CreateEditorStateWithDoc = addMDHOC(CreateContentState,  '/docs/createContentState.md');
export const ComplexDecoratorStateWithDoc = addMDHOC(ComplexDecorator,  '/docs/complexDecorator.md');
